In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("C:/Users/METRO/Downloads/Data_Analyst_Assignment/Qure.ai Data Analyst Assignment Files New (1)/Qure.ai Data Analyst Assignment Files/confirmed-covid-19-deaths-in-us-by-state-and-county copy.csv")

In [3]:
data.head()

Unnamed: 0  county_fips            county_name state_name  state_fips  \
0           0            0  Statewide Unallocated         AL           1   
1           1            0  Statewide Unallocated         AL           1   
2           2            0  Statewide Unallocated         AL           1   
3           3            0  Statewide Unallocated         AL           1   
4           4            0  Statewide Unallocated         AL           1   

         date  deaths  lat  long geometry  
0  2020-01-22       0  NaN   NaN      NaN  
1  2020-01-23       0  NaN   NaN      NaN  
2  2020-01-24       0  NaN   NaN      NaN  
3  2020-01-25       0  NaN   NaN      NaN  
4  2020-01-26       0  NaN   NaN      NaN

In [52]:
#for missing values
print(data['lat'].unique())
print(data['long'].unique())

[        nan 32.53952745 30.72774991 ... 41.2878183  43.90451606
 43.83961191]
[          nan  -86.64408227  -87.72207058 ... -110.5475782  -107.680187
 -104.5674881 ]


In [53]:
data['lat']=data['lat'].fillna(data['lat'].mean(),inplace=True)

In [50]:
data['state_name'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [6]:
data1=pd.read_csv("C:/Users/METRO/Downloads/Data_Analyst_Assignment/Qure.ai Data Analyst Assignment Files New (1)/Qure.ai Data Analyst Assignment Files/covid-19-state-level-data copy.csv")
data1.head()

Unnamed: 0        date       state  fips  cases  deaths
0           0  2020-01-21  Washington    53      1       0
1           1  2020-01-22  Washington    53      1       0
2           2  2020-01-23  Washington    53      1       0
3           3  2020-01-24    Illinois    17      1       0
4           4  2020-01-24  Washington    53      1       0

In [8]:
data1.drop(columns=['Unnamed: 0'],axis=1,inplace=True)

In [9]:
data1.head()

date       state  fips  cases  deaths
0  2020-01-21  Washington    53      1       0
1  2020-01-22  Washington    53      1       0
2  2020-01-23  Washington    53      1       0
3  2020-01-24    Illinois    17      1       0
4  2020-01-24  Washington    53      1       0

In [11]:
data1['cases'].unique()

array([    1,     2,     3, ..., 86994, 56576, 54114], dtype=int64)

In [12]:
data1['fips'].unique()

array([53, 17,  6,  4, 25, 55, 48, 31, 49, 41, 12, 36, 44, 13, 33, 37, 34,
        8, 24, 32, 47, 15, 18, 21, 27, 40, 42, 45, 11, 20, 29, 50, 51,  9,
       19, 22, 39, 26, 46,  5, 10, 28, 35, 38, 56,  2, 23,  1, 16, 30, 72,
       78, 66, 54, 69], dtype=int64)

In [14]:
data1['deaths'].unique()

array([   0,    1,    3, ..., 6515, 1633,  916], dtype=int64)

In [15]:
data1.isna().sum()

date      0
state     0
fips      0
cases     0
deaths    0
dtype: int64

In [22]:
data1.duplicated().sum()

0

In [54]:
data.isna().sum()

county_fips         0
county_name         0
state_name          0
state_fips          0
date                0
deaths              0
lat            600660
long             9964
geometry         9964
year                0
month               0
day                 0
dtype: int64

In [55]:
data.head()

county_fips            county_name state_name  state_fips        date  \
0            0  Statewide Unallocated         AL           1  2020-01-22   
1            0  Statewide Unallocated         AL           1  2020-01-23   
2            0  Statewide Unallocated         AL           1  2020-01-24   
3            0  Statewide Unallocated         AL           1  2020-01-25   
4            0  Statewide Unallocated         AL           1  2020-01-26   

   deaths   lat  long geometry  year  month  day  
0       0  None   NaN      NaN  2020      1   22  
1       0  None   NaN      NaN  2020      1   23  
2       0  None   NaN      NaN  2020      1   24  
3       0  None   NaN      NaN  2020      1   25  
4       0  None   NaN      NaN  2020      1   26

In [56]:
data.duplicated().sum()

0

In [57]:
data['county_fips'].unique()

array([    0,  1001,  1003, ..., 56041, 56043, 56045], dtype=int64)

In [58]:
data['geometry'].unique()

array([nan, 'POINT (-86.64408227 32.53952745)',
       'POINT (-87.72207058 30.72774991)', ...,
       'POINT (-110.5475782 41.2878183)',
       'POINT (-107.680187 43.90451606)',
       'POINT (-104.5674881 43.83961191)'], dtype=object)

In [59]:
data['county_name'].unique()

array(['Statewide Unallocated', 'Autauga County', 'Baldwin County', ...,
       'Uinta County', 'Washakie County', 'Weston County'], dtype=object)

In [60]:
data['year']=pd.DatetimeIndex(data['date']).year
data['month']=pd.DatetimeIndex(data['date']).month
data['day']=pd.DatetimeIndex(data['date']).day

In [61]:
data['state_name'].count()

600660

In [62]:
data.drop(columns=['Unnamed: 0'],inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [64]:
data['state_fips'].unique()

array([ 1,  2,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56],
      dtype=int64)

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600660 entries, 0 to 600659
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   county_fips  600660 non-null  int64  
 1   county_name  600660 non-null  object 
 2   state_name   600660 non-null  object 
 3   state_fips   600660 non-null  int64  
 4   date         600660 non-null  object 
 5   deaths       600660 non-null  int64  
 6   lat          0 non-null       object 
 7   long         590696 non-null  float64
 8   geometry     590696 non-null  object 
 9   year         600660 non-null  int64  
 10  month        600660 non-null  int64  
 11  day          600660 non-null  int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 55.0+ MB
